<a href="https://colab.research.google.com/github/Pruthvi-Parmar/Data_Mining_Stuff/blob/main/LAB_1/two.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.array([1, 2, 3, 4])
print(a)


[1 2 3 4]


In [ ]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [ ]:
a.ndim


1

In [ ]:
b.ndim

2

In [ ]:
a.shape # row column

(4,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

8

In [ ]:
a.size

4

In [ ]:
b.size

6

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
a.nbytes

32

In [ ]:
b.nbytes

48

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
a[1,3]

9

In [ ]:
a[1,:]

array([ 6,  7,  8,  9, 10])

In [ ]:
a[:,2]

array([3, 8])

In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a[0,1,1]

4

In [ ]:
a[:,1,:] = [[9,9],[8,8]]

In [ ]:
print(a)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
a

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [ ]:
np.full_like(a,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [ ]:
np.random.rand(4,2)

array([[0.66015704, 0.71828459],
       [0.44100565, 0.27254613],
       [0.05104788, 0.20312669],
       [0.45747592, 0.75167999]])

In [ ]:
np.random.randint(5,10,size=(3,3))

array([[5, 8, 8],
       [6, 5, 6],
       [6, 9, 8]])

In [ ]:


import numpy as np


matrix = np.ones((5, 5), dtype=int)
matrix[1:4, 1:4] = 0
matrix[2,2] = 9

matrix

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
a = np.identity(5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.linalg.det(a)

1.0

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats)

21

In [ ]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])